### PR TITLE
feat(LabelBreakdownScene): display an error message when the request fails

### PR DESCRIPTION
**Pull request by matyax**
Closes https://github.com/grafana/explore-logs/issues/402

Message:

imagen

Open for suggestions for the error message. The important part is that:
- It should let the user know what happened.
- It should offer at least one workaround.

### CODE REVIEW

**Comment by matryer** [comment]
nice @matyax - this is an improvement. I will open a separate issue to discuss auto-retries.

**Review by matryer — APPROVED** [review]
LGTM

**Comment by svennergr** [comment]
Just a nit, but do we have a way to make the `Alert` less alerty and more warningy? What I mean is less red, more orange/informative?

**Comment by matyax** [comment]
Good idea. Made it a warning instead of error.

**Comment by matyax** [comment]
Good idea. Made it a warning instead of error. We should keep this type in mind to be consistent.

**Review by svennergr — APPROVED** [review]

**Pull request merged**
