### PR TITLE
feat(feedback): move feedback button

### PR DESCRIPTION
**Pull request by svennergr**
Moves the feedback button:
https://raintank-corp.slack.com/archives/C05FWM2DN07/p1722364395732199

image

### CODE REVIEW

**Comment by matyax** [comment]
Looks great there, but I would at least duplicate the gap between "Feedback" and the time picker.

test

**Comment by matyax** [comment]
E.g.
Gap 8px

imagen


Gap 4px

imagen

**Review by matyax — APPROVED** [review]

**Comment by matyax** [comment]
Maybe we need to position the button without changing the gap, because it's currently misaligned, and will be even more with a bigger gap.

gap

**Comment by svennergr** [comment]
@matyax not the biggest fan, but what do you think about

```
      position: 'relative',
      top: theme.spacing(-1),
```
image

**Comment by matyax** [comment]
Yeah, that should do it 👍 . Thanks!

**Review by matyax — APPROVED** [review]
:stamp:

**Pull request merged**
