### PR TITLE
Add make docs procedure

### PR DESCRIPTION
**Pull request by jdbaldry**
Add the tooling for rendering a local preview of the documentation and a procedure to keep it up to date.

For more information, refer to https://grafana.com/docs/writers-toolkit/review/.

Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

### CODE REVIEW

**Review by JStickler — APPROVED** [review]
[docs team]  LGTM.  

Do we need anything in the way of workflows to publish to the website?

**Comment by jdbaldry** [comment]
For publishing "next" content, we first need to merge https://github.com/grafana/website/pull/20393 to prevent publishing prematurely and then I an install something like https://github.com/grafana/grafana/blob/main/.github/workflows/publish-technical-documentation-next.yml to do the publishing. 

Do we have an issue somewhere that explains where we want the docs to show up in the website?

**Comment by JStickler** [comment]
>Do we have an issue somewhere that explains where we want the docs to show up in the website?

We're having an information architecture meeting on Tuesday to figure that out.

**Comment by jdbaldry** [comment]
https://github.com/grafana/explore-logs/pull/494/ was merged that will sync documentation

**Review by matryer — APPROVED** [review]
LGTM

**Pull request merged**
