### PR TITLE
feat(breadcrumbs): add service name to breadcrumbs

### PR DESCRIPTION
**Pull request by gtk-grafana**
Fixes: https://github.com/grafana/explore-logs/issues/428

https://github.com/grafana/explore-logs/assets/109082771/67005192-2c1e-4653-93cb-6828eac23844

### CODE REVIEW

**Comment by gtk-grafana** [comment]
I think this is the desired functionality, since we don't have anything unique to link the service name to?

**Review by matyax — COMMENTED** [review]
I like this! My only comment is that the service name should take you to the service view and not back to the home page. See:

https://github.com/grafana/explore-logs/assets/1069378/a58d82bc-d23c-4ac3-8928-56fb34a459a7

**Comment by gtk-grafana** [comment]
Kicking to draft while we investigate fixes to https://github.com/grafana/explore-logs/issues/351.

**Comment by gtk-grafana** [comment]
Closing as this is impacted by https://github.com/grafana/explore-logs/pull/477, I don't think scenes will allow us to customize breadcrumbs like this without modifications to scenes.

**Pull request closed without merging**
