### PR TITLE
Logs volume: Fix active state of series based on the filter's state

### PR DESCRIPTION
**Pull request by matyax**
Series visibility + filters state:

https://github.com/user-attachments/assets/e7f0bc6b-07c4-421e-9e0f-e90b3a9d0a01

Fixes https://github.com/grafana/explore-logs/issues/686

Extra/minor changes:
- Renamed functions for consistency with their purpose.
- Renamed variables for readability and consistency with their purpose.
- Fixed typo in function name.
- Used variable getters from variables.ts.
- Added comments to levels functions.

### CODE REVIEW

**Comment by gtk-grafana** [comment]
Also multiple includes "should" show no-data, but I'm conflicted if we actually want this.
image

**Comment by matyax** [comment]
@gtk-grafana This has been greatly refactored. If you have time, I'd appreciate if you can take it for a spin again, to see if there's another combo that we're not correctly supporting. I'll continue testing as well.

**Comment by gtk-grafana** [comment]
Much better, the behavior in the logs volume panel is working as I'd expect it to now.
One (maybe two) problem that I still see:
image
All labels get added to the stream selector for the labels queries besides detected_field.

Looks like the queries in the labels panel are now ignoring the detected_level filters. in https://github.com/grafana/explore-logs/pull/682 I add a new method for adding custom structured metadata to queries without needing to interpolate. That might be helpful here?

**Comment by matyax** [comment]
Great, thanks @gtk-grafana ! 

> All labels get added to the stream selector for the labels queries besides detected_field.

Do you mind merging these fixes and following up this with https://github.com/grafana/explore-logs/issues/700 ?

**Comment by gtk-grafana** [comment]
Nope!

**Review by gtk-grafana — APPROVED** [review]

**Pull request merged**
