### PR TITLE
Filters: add support for filters with multiple values

### PR DESCRIPTION
**Pull request by matyax**
Aimed to fix https://github.com/grafana/explore-logs/issues/691 , this PR adds support for all fields and labels with multiple values.

Fields demo:

https://github.com/user-attachments/assets/984f4d25-aa11-409b-9e4e-19a708bdf9f1

Labels demo:

https://github.com/user-attachments/assets/cfd97a70-a94e-4901-ac1f-15269ec0fc86

### CODE REVIEW

**Comment by matyax** [comment]
I did this all with fields, but didn't check labels. Looking now 🧐

**Comment by matyax** [comment]
Added support for labels too.

**Comment by gtk-grafana** [comment]
This works, but the value breakdown UIs don't support including multiple yet.

**Comment by matyax** [comment]
Oh absolutely. But you can get there by starting with exclusions.

**Comment by gtk-grafana** [comment]
It's a good way to keep the size of the PR down. I'm fine with merging this as is and following up in the UI (which I think will be a bigger PR)

**Comment by matyax** [comment]
Agree. If you would like to follow that up, since you recently refactored it, go for it. Otherwise I'll follow this up. Thanks!

**Comment by gtk-grafana** [comment]
Might be nice to use a multi select variable instead of taking up all this space for variables? Can you create 2 two follow up issues (you can assign the changing of the queries in the breakdowns to allow for multiple includes) so we don't lose track over the weekend?

**Review by gtk-grafana — APPROVED** [review]
LGTM, works well locally

**Comment by matyax** [comment]
Created #723 and #724

**Pull request merged**
