### PR TITLE
feat(patterns): implement undo include and undo exclude pattern in table

### PR DESCRIPTION
**Pull request by ivanahuckova**
1. Implement undo include/exclude in table - by visually toggling severity of a new joined button
2. Unify naming - include/exclude instead of select
image

Part of https://github.com/grafana/explore-logs/issues/354

### CODE REVIEW

**Comment by ivanahuckova** [comment]
> round the outer corners a bit more
I am against this as this have the same border radius as every other button/radio button/input in our design system. I don't think we want to create something that looks different than anything else in grafana.
 
 > remove the line in between the buttons, use a background colour rather than border
✅ 

> still using one of the sanctioned background colours

Not sure I understand what do you mean by that
image

**Comment by gtk-grafana** [comment]
@zizzpudding Just wanted to point out that this PR will be changing the copy back to "Include" from "select" even the user can only select a single include pattern. Is there anything we want do to hint to the user that exclude behaves differently then include?

image
image

**Comment by ivanahuckova** [comment]
>user can only select a single include pattern. Is there anything we want do to hint to the user that exclude behaves differently then include?

@gtk-grafana @svennergr actually proved that you can use multiple include patterns, which we want to implement next.

**Review by gtk-grafana — APPROVED** [review]
Code looks good (thanks for getting it cleaned up!) and works well locally! Thanks Ivana!

**Pull request merged**
