### PR TITLE
chore: reorganize files to enhance collocation

### PR DESCRIPTION
**Pull request by ivanahuckova**
One of the main principles we discussed and appreciate in code structure is collocation — having tests, types, and components close to where they are used. Following this pattern (after a discussion with @matyax), I have created a PR that enhances collocation.

Components are placed next to other components/scenes that use them, instead of grouping buttons/inputs together by type. This approach is also used in the logs app repository.

image

### CODE REVIEW

**Comment by svennergr** [comment]
What's the difference between `IndexScene` and `ServiceSelectionScene`? Also, why is `Pattern.tsx` in `IndexScene`?

**Comment by ivanahuckova** [comment]
>  Also, why is Pattern.tsx in IndexScene?

Pattern is component only used in Index Scenes - it is this component:

image

**Comment by ivanahuckova** [comment]
> What's the difference between IndexScene and ServiceSelectionScene

Index scene is the top scene and it either renders search service or service index.

**Review by matyax — APPROVED** [review]
Feel free to continue the discussion. Giving my 👍 because I like this structure a lot, great work!

**Comment by svennergr** [comment]
> > What's the difference between IndexScene and ServiceSelectionScene
> 
> Index scene is the top scene and it either renders service selection scene or service scene.

That's were this pattern of putting components "where they are used" get's a bit ambiguous, since the pattern selector is only visible for `ServiceScenes`, right?

**Comment by ivanahuckova** [comment]
> That's were this pattern of putting components "where they are used" get's a bit ambiguous, since the pattern selector is only visible for ServiceScenes, right?

Well, it is only used in IndexScene and I think what you are talking about is more about how to refactor this mess of an Index Scene.

**Review by svennergr — APPROVED** [review]

**Pull request merged**
